export const MOCK_EXAMS = Object.freeze([
  Object.freeze({
    id: "mock-original-01",
    title: "原创完整模拟卷 01 · 综合能力训练",
    year: "本站",
    examType: "原创模拟",
    sourceType: "original",
    sourceLabel: "本站原创模拟卷",
    sourceDetail: "依据CET-6题型能力要求独立编写，不是官方真题，也不复制商业题库。",
    description: "按写作、听力、阅读、翻译顺序完成；题序固定，答案和草稿会自动保存在当前账户。",
    durationMinutes: 130,
    sections: Object.freeze([
      Object.freeze({
        id: "writing",
        module: "writing",
        title: "写作",
        minutes: 30,
        instruction: "审题、列提纲并完成一篇完整作文。提交后可查看本站自查建议。",
        itemIds: Object.freeze(["write-ai-study-boundaries"]),
      }),
      Object.freeze({
        id: "listening",
        module: "listening",
        title: "听力",
        minutes: 35,
        instruction: "先独立听材料并作答；可按需要回听，但不要查看文本。",
        itemIds: Object.freeze([
          "listen-urban-library",
          "listen-campus-garden",
          "listen-lab-schedule",
          "listen-bike-service",
          "listen-sleep-routine",
          "listen-citizen-science",
          "listen-refill-report",
          "listen-job-shadowing",
          "listen-spaced-practice",
          "listen-urban-trees",
        ]),
      }),
      Object.freeze({
        id: "reading",
        module: "reading",
        title: "阅读",
        minutes: 35,
        instruction: "先读题干再定位证据；选词填空和长篇匹配要记录词性、同义替换和逻辑关系。",
        itemIds: Object.freeze([
          "read-micro-breaks",
          "read-local-museums",
          "read-digital-notes",
          "read-community-markets",
          "read-quiet-technology",
          "read-public-benches",
          "read-cloze-campus-energy",
          "read-cloze-peer-feedback",
          "read-matching-learning-spaces",
          "read-matching-community-projects",
        ]),
      }),
      Object.freeze({
        id: "translation",
        module: "translation",
        title: "翻译",
        minutes: 30,
        instruction: "先拆分中文长句，再完成译文并检查时态、主谓、搭配和文化表达。",
        itemIds: Object.freeze(["trans-high-speed-rail"]),
      }),
    ]),
  }),
  Object.freeze({
    id: "mock-original-02",
    title: "原创完整模拟卷 02 · 主题迁移训练",
    year: "本站",
    examType: "原创模拟",
    sourceType: "original",
    sourceLabel: "本站原创模拟卷",
    sourceDetail: "依据CET-6题型能力要求独立编写，不是官方真题，也不复制商业题库。",
    description: "更换写译主题和听读材料，按完整考试顺序训练迁移能力；题序固定、答案自动保存。",
    durationMinutes: 130,
    sections: Object.freeze([
      Object.freeze({
        id: "writing",
        module: "writing",
        title: "写作",
        minutes: 30,
        instruction: "围绕公共服务与城市生活完成一篇完整作文。",
        itemIds: Object.freeze(["write-public-transport"]),
      }),
      Object.freeze({
        id: "listening",
        module: "listening",
        title: "听力",
        minutes: 35,
        instruction: "先预测问题方向，再抓最终决定、转折和因果信息。",
        itemIds: Object.freeze([
          "listen-campus-garden",
          "listen-lab-schedule",
          "listen-bike-service",
          "listen-sleep-routine",
          "listen-citizen-science",
          "listen-refill-report",
          "listen-job-shadowing",
          "listen-spaced-practice",
          "listen-urban-trees",
          "listen-urban-library",
        ]),
      }),
      Object.freeze({
        id: "reading",
        module: "reading",
        title: "阅读",
        minutes: 35,
        instruction: "按题干关键词定位，区分原文证据、同义替换和干扰项。",
        itemIds: Object.freeze([
          "read-local-museums",
          "read-digital-notes",
          "read-community-markets",
          "read-quiet-technology",
          "read-public-benches",
          "read-cloze-campus-energy",
          "read-cloze-peer-feedback",
          "read-matching-learning-spaces",
          "read-matching-community-projects",
          "read-micro-breaks",
        ]),
      }),
      Object.freeze({
        id: "translation",
        module: "translation",
        title: "翻译",
        minutes: 30,
        instruction: "拆分长句并检查文化主题词、时态、主谓和搭配。",
        itemIds: Object.freeze(["trans-community-sports"]),
      }),
    ]),
  }),
  Object.freeze({
    id: "mock-original-03",
    title: "原创完整模拟卷 03 · 冲刺表达训练",
    year: "本站",
    examType: "原创模拟",
    sourceType: "original",
    sourceLabel: "本站原创模拟卷",
    sourceDetail: "依据CET-6题型能力要求独立编写，不是官方真题，也不复制商业题库。",
    description: "重点练习文化、科技、教育与社会责任主题，适合阶段测验和冲刺复盘。",
    durationMinutes: 130,
    sections: Object.freeze([
      Object.freeze({
        id: "writing",
        module: "writing",
        title: "写作",
        minutes: 30,
        instruction: "围绕文化传承与校园发展完成一篇观点讨论作文。",
        itemIds: Object.freeze(["write-campus-traditions"]),
      }),
      Object.freeze({
        id: "listening",
        module: "listening",
        title: "听力",
        minutes: 35,
        instruction: "重点识别讲座主旨、总结句和观点转折。",
        itemIds: Object.freeze([
          "listen-spaced-practice",
          "listen-job-shadowing",
          "listen-refill-report",
          "listen-citizen-science",
          "listen-sleep-routine",
          "listen-bike-service",
          "listen-lab-schedule",
          "listen-urban-trees",
          "listen-campus-garden",
          "listen-urban-library",
        ]),
      }),
      Object.freeze({
        id: "reading",
        module: "reading",
        title: "阅读",
        minutes: 35,
        instruction: "先看题干再读定位句，完成细节、推断、选词和匹配任务。",
        itemIds: Object.freeze([
          "read-quiet-technology",
          "read-public-benches",
          "read-community-markets",
          "read-digital-notes",
          "read-local-museums",
          "read-micro-breaks",
          "read-cloze-peer-feedback",
          "read-cloze-campus-energy",
          "read-matching-community-projects",
          "read-matching-learning-spaces",
        ]),
      }),
      Object.freeze({
        id: "translation",
        module: "translation",
        title: "翻译",
        minutes: 30,
        instruction: "围绕公共科学、数字社会和文化主题完成汉译英。",
        itemIds: Object.freeze(["trans-science-education"]),
      }),
    ]),
  }),
]);

export const MOCK_EXAM_BY_ID = Object.freeze(
  Object.fromEntries(MOCK_EXAMS.map((exam) => [exam.id, exam])),
);

const REAL_EXAM_YEARS = Object.freeze(["2026", "2025", "2024", "2023", "2022", "2021", "2020", "2019", "2018"]);
const REAL_EXAM_TYPES = Object.freeze([
  ["written", "笔试整套"],
  ["listening", "听力专项"],
  ["reading", "阅读专项"],
  ["writing-translation", "写作与翻译"],
]);

export const REAL_EXAM_INDEX = Object.freeze(
  REAL_EXAM_YEARS.flatMap((year) => REAL_EXAM_TYPES.map(([type, typeLabel]) => ({
    id: `cet6-${year}-${type}`,
    year,
    type,
    typeLabel,
    title: `${year}年${typeLabel}真题入口`,
    sourceType: "external-index",
    sourceLabel: "官方入口 + 外部平台索引",
    sourceDetail: "本站不存储、不镜像完整真题、音频或付费解析；请在官方入口或你有权使用的平台中完成训练。",
    links: [
      { name: "CET官方网站", url: "https://cet.neea.edu.cn/" },
      { name: "星火英语", url: "https://www.sparke.cn/" },
      { name: "可可英语", url: "https://www.kekenet.com/" },
    ],
  }))),
);
