const listeningItem = (id, title, type, theme, difficulty, script, question, options, answer, evidence, explanation, optionAnalysis, knowledgePoints) => ({
  id,
  kind: "single",
  title,
  type,
  theme,
  difficulty,
  script,
  question,
  options,
  answer,
  evidence,
  explanation,
  optionAnalysis,
  questionType: knowledgePoints[0],
  knowledgePoints,
});

const carefulReading = (id, title, theme, difficulty, passage, question, options, answer, evidence, explanation, optionAnalysis, knowledgePoints) => ({
  id,
  kind: "careful",
  title,
  type: "仔细阅读",
  theme,
  difficulty,
  passage,
  question,
  options,
  answer,
  evidence,
  explanation,
  optionAnalysis,
  questionType: knowledgePoints[0],
  knowledgePoints,
});

export const SUPPLEMENTAL_PRACTICE_CONTENT = Object.freeze({
  listening: Object.freeze([
    listeningItem(
      "listen-lab-schedule",
      "长对话：调整实验室参观时间",
      "长对话",
      "校园学习",
      "基础",
      "Nina and Eric are preparing a report on renewable energy. Nina suggests visiting the engineering laboratory on Friday afternoon, but Eric has a compulsory statistics workshop then. He proposes Thursday morning instead. Nina explains that the laboratory technician will be training new staff on Thursday, so visitors cannot enter. After checking their schedules, they agree to visit early Friday morning and use the afternoon to organize their notes.",
      "When will the students visit the laboratory?",
      ["Thursday morning", "Thursday afternoon", "Friday morning", "Friday afternoon"],
      2,
      "They agree to visit early Friday morning.",
      "周四因技术人员培训不可进入，周五下午原计划也与课程冲突，最终时间是周五早上。",
      ["该时间被实验室培训安排否定。", "对话没有提出周四下午。", "正确，agree to visit对应最终决定。", "周五下午用于整理笔记。"],
      ["时间定位", "方案排除", "最终决定"],
    ),
    listeningItem(
      "listen-bike-service",
      "长对话：校园自行车维修服务",
      "长对话",
      "公共服务",
      "进阶",
      "A student representative tells the transport manager that the campus bicycle repair point is popular but difficult to use between classes. The manager first assumes that students want more tools. The representative clarifies that the real problem is the booking system: it only shows whether a whole morning or afternoon is full, not which twenty-minute periods remain available. The manager promises to introduce shorter booking slots before considering longer opening hours.",
      "What change will the manager make first?",
      ["Purchase additional repair tools", "Add shorter appointment periods", "Keep the service open overnight", "Move the repair point to another building"],
      1,
      "The manager promises to introduce shorter booking slots.",
      "学生真正提出的是预约信息过于粗略，负责人首先改进预约时段，而不是扩充设备或营业时间。",
      ["负责人最初误解为工具不足。", "正确，shorter appointment periods同义替换shorter booking slots。", "只提到以后可能延长开放时间。", "没有讨论搬迁。"],
      ["问题澄清", "同义替换", "先后顺序"],
    ),
    listeningItem(
      "listen-sleep-routine",
      "听力篇章：稳定作息与学习效率",
      "听力篇章",
      "健康管理",
      "基础",
      "Students often respond to a busy week by sleeping very little on weekdays and staying in bed much longer at weekends. This may feel like recovery, but large changes in waking time can make Monday morning more difficult. Sleep researchers therefore recommend a reasonably stable schedule. They do not suggest ignoring tiredness. Instead, students should protect a regular bedtime and use a short daytime rest when necessary rather than repeatedly shifting the entire sleep cycle.",
      "What is the main recommendation of the passage?",
      ["Avoid all daytime sleep", "Study late whenever work increases", "Maintain a fairly regular sleep schedule", "Sleep as long as possible every weekend"],
      2,
      "Sleep researchers therefore recommend a reasonably stable schedule.",
      "篇章先描述周末补觉造成的问题，再提出保持相对稳定作息的核心建议。",
      ["原文允许必要时短暂休息。", "熬夜是需要避免的情况。", "正确，regular对应stable。", "周末大幅改变起床时间会带来问题。"],
      ["主旨题", "因果关系", "建议识别"],
    ),
    listeningItem(
      "listen-citizen-science",
      "听力篇章：城市鸟类观察项目",
      "听力篇章",
      "科学参与",
      "进阶",
      "A city university invited residents to record birds they saw in parks during spring. At first, the biology department expected the project mainly to provide a larger amount of data. The records did help researchers identify changes in migration dates. However, a second benefit became equally important: participants began to understand why observations must be made at similar times and described in consistent language. The project therefore taught the public how reliable evidence is collected.",
      "What additional benefit did the project produce?",
      ["It reduced the number of migrating birds", "It taught participants how evidence is collected", "It replaced professional biological research", "It allowed parks to close earlier"],
      1,
      "The project therefore taught the public how reliable evidence is collected.",
      "题目询问额外收益，结尾指出公众理解了规范观察和可靠证据的形成过程。",
      ["项目记录变化而非减少鸟类。", "正确，结尾总结额外教育价值。", "公众参与没有取代专业研究。", "材料没有涉及公园关闭时间。"],
      ["转折后信息", "总结句", "目的与结果"],
    ),
    listeningItem(
      "listen-refill-report",
      "报道：公共场所增设饮水点",
      "讲话/报道/讲座",
      "绿色生活",
      "基础",
      "The local council has installed twenty water refill stations near sports centers, libraries and transport hubs. The decision followed a six-week survey showing that many residents bought bottled water because they could not easily find safe drinking water while travelling. Officials will compare plastic waste figures before and after the installation. If the reduction is significant, another thirty stations will be added next year.",
      "Why were the refill stations installed?",
      ["Residents lacked convenient access to drinking water", "Libraries requested new sports equipment", "The council wanted to raise transport fares", "Bottled water companies funded the project"],
      0,
      "Many residents bought bottled water because they could not easily find safe drinking water while travelling.",
      "调查发现外出时缺少方便、安全的饮水渠道，因此增设饮水点。",
      ["正确，对应because后的原因。", "地点包含图书馆，但与器材无关。", "没有提到交通费用。", "没有说明企业资助。"],
      ["原因细节", "数字干扰", "条件信息"],
    ),
    listeningItem(
      "listen-job-shadowing",
      "报道：短期岗位观察计划",
      "讲话/报道/讲座",
      "就业发展",
      "进阶",
      "A graduate employment center recently tested a one-day job-shadowing program. Students followed an employee, observed meetings and asked questions about routine tasks. Organizers expected the program to confirm students' career choices. Instead, many participants reported that its greatest value was discovering which parts of a job did not suit them. The center will keep the program because eliminating an unsuitable option can save as much time as identifying an attractive one.",
      "What did many students value most about the program?",
      ["Receiving immediate job offers", "Learning which work might not suit them", "Avoiding all workplace meetings", "Confirming every previous career plan"],
      1,
      "Its greatest value was discovering which parts of a job did not suit them.",
      "instead引出与预期不同的结果：学生最看重排除不适合自己的职业方向。",
      ["项目没有承诺工作机会。", "正确，原句直接说明。", "学生需要观察会议而非避免会议。", "实际结果与全部确认原计划相反。"],
      ["观点转折", "最高级定位", "预期与结果"],
    ),
    listeningItem(
      "listen-spaced-practice",
      "讲座：为什么间隔练习更有效",
      "讲话/报道/讲座",
      "学习科学",
      "进阶",
      "In today's lecture, we will compare repeated practice with spaced practice. Completing the same exercise five times in one evening may create a strong feeling of fluency. Yet that feeling partly comes from the fact that the answer is still active in short-term memory. When practice is separated across several days, retrieval becomes harder, but the learner must rebuild the path to the information. This extra effort is one reason later recall is often stronger.",
      "Why can spaced practice improve later recall?",
      ["It removes the need to retrieve information", "It keeps every answer in short-term memory", "It requires learners to reconstruct access to information", "It makes practice feel easier immediately"],
      2,
      "The learner must rebuild the path to the information.",
      "间隔后提取更困难，学习者必须重新建立通向信息的路径，这种努力有利于长期回忆。",
      ["间隔练习增加而非取消提取。", "短期记忆解释集中重复的流畅感。", "正确，reconstruct对应rebuild。", "材料指出间隔练习当下更难。"],
      ["因果推断", "概念解释", "同义替换"],
    ),
    listeningItem(
      "listen-urban-trees",
      "讲座：城市树木的降温作用",
      "讲话/报道/讲座",
      "城市环境",
      "挑战",
      "Urban trees cool streets in two ways. Their leaves block part of the sun's energy, while water released from the leaves also removes heat from the surrounding air. However, planting any tree anywhere is not enough. Young trees need water, suitable soil and space for their roots. A city may announce an impressive planting target, but the long-term benefit depends on how many trees remain healthy ten years later.",
      "What does the speaker emphasize about urban tree programs?",
      ["The number planted is the only meaningful measure", "Long-term maintenance determines their real benefit", "Young trees require almost no water", "Trees cool streets only by creating shade"],
      1,
      "The long-term benefit depends on how many trees remain healthy ten years later.",
      "讲者先解释两种降温机制，随后强调不能只看栽种数量，长期养护和存活才决定效果。",
      ["结尾反驳只看数量。", "正确，对应long-term benefit。", "原文明确说幼树需要水。", "除遮阴外还有叶片蒸腾降温。"],
      ["讲者观点", "让步转折", "多重机制"],
    ),
  ]),
  reading: Object.freeze([
    carefulReading(
      "read-digital-notes",
      "仔细阅读：数字笔记是否越多越好",
      "学习方法",
      "基础",
      "Digital note-taking tools make it easy to store large amounts of information, but storage is not the same as learning. Students sometimes copy complete slides because they fear missing a detail. The result is a record that is accurate but difficult to review. More effective notes are selective: they identify the central claim, preserve necessary evidence and show how one idea connects with another. A useful test is whether the student can explain the page without reading every sentence aloud.",
      "What does the passage identify as a feature of effective notes?",
      ["They reproduce every slide completely", "They focus on central ideas and connections", "They avoid recording any evidence", "They can only be understood by their writer"],
      1,
      "More effective notes are selective: they identify the central claim, preserve necessary evidence and show how one idea connects with another.",
      "有效笔记不是复制全部内容，而是筛选核心观点、必要证据和观点之间的联系。",
      ["这是低效做法。", "正确，概括了selective后的三个特点。", "有效笔记仍保留必要证据。", "文章没有要求只能本人理解。"],
      ["细节概括", "对比关系", "主旨词定位"],
    ),
    carefulReading(
      "read-community-markets",
      "仔细阅读：社区市集的长期价值",
      "社区经济",
      "进阶",
      "Weekend markets are often promoted as places where small producers can sell directly to customers. Their economic value matters, but repeated face-to-face contact may be just as important. Producers learn which products confuse customers and which explanations build trust. Customers, in turn, understand why seasonal supply changes and why handmade goods may cost more. Markets that survive beyond their first year usually create these relationships instead of relying only on entertainment or temporary publicity.",
      "According to the passage, what helps a weekend market survive?",
      ["Depending mainly on temporary publicity", "Building repeated relationships between producers and customers", "Keeping production methods secret", "Selling only products available in every season"],
      1,
      "Markets that survive beyond their first year usually create these relationships.",
      "末句指出长期存续依靠生产者与消费者之间反复形成的理解和信任。",
      ["末句明确否定只依靠短期宣传。", "正确，these relationships承接前文互动。", "生产者需要解释而不是保密。", "文章说明季节供应会变化。"],
      ["指代判断", "段尾结论", "因果关系"],
    ),
    carefulReading(
      "read-quiet-technology",
      "仔细阅读：不显眼的技术改进",
      "科技创新",
      "进阶",
      "Public discussion of innovation often focuses on dramatic inventions. Yet many improvements are quiet changes to an existing system. A clearer hospital form can reduce mistakes. A better timetable can shorten unnecessary waiting. These changes may not require advanced machines, but they depend on careful observation of where people become confused or delayed. Innovation should therefore be judged not only by technical novelty but also by whether it solves a real problem reliably.",
      "How does the author suggest innovation should be judged?",
      ["Only by the complexity of its technology", "By whether it reliably solves an actual problem", "By the amount of publicity it receives", "Only by whether it creates a new machine"],
      1,
      "Innovation should therefore be judged not only by technical novelty but also by whether it solves a real problem reliably.",
      "作者通过表格和时刻表等例子说明，创新价值还取决于能否可靠解决真实问题。",
      ["作者反对只看技术复杂度。", "正确，直接对应末句。", "材料没有把宣传作为标准。", "安静改进可能不涉及新机器。"],
      ["作者观点", "举例论证", "not only...but also"],
    ),
    carefulReading(
      "read-public-benches",
      "仔细阅读：公共座椅与城市体验",
      "城市公共空间",
      "挑战",
      "A bench may appear to be a minor piece of urban infrastructure, yet its location influences who can comfortably use a street. Older adults may need a place to rest between a bus stop and a clinic. Parents may value seating that allows them to watch children safely. If benches are placed only where they look attractive in photographs, they may fail the people who need them most. Good placement begins with observing journeys, waiting times and physical effort rather than treating seating as decoration.",
      "What is the main point of the passage?",
      ["Public seating should be planned around users' actual journeys", "Benches should mainly improve photographs of a city", "Only older adults need public seating", "Urban infrastructure should avoid simple objects"],
      0,
      "Good placement begins with observing journeys, waiting times and physical effort.",
      "文章用老年人和家长的需求说明，座椅位置应依据真实出行过程，而不是只考虑装饰效果。",
      ["正确，概括结尾和全部例子。", "这是文章批评的做法。", "家长等其他群体同样需要。", "文章肯定简单设施也有重要作用。"],
      ["主旨题", "例子归纳", "观点对比"],
    ),
    {
      id: "read-cloze-campus-energy",
      kind: "cloze",
      title: "选词填空：校园节能项目",
      type: "选词填空",
      theme: "绿色校园",
      difficulty: "基础",
      knowledgePoints: ["词性判断", "固定搭配", "上下文逻辑"],
      segments: [
        "A university energy team found that many classroom lights remained on after lessons. Instead of relying only on warning signs, the team decided to ",
        " the problem by examining when and where it occurred. Students then designed a simple dashboard that made daily electricity use more ",
        ". The information encouraged departments to compare results and ",
        " practical changes. After one term, energy use had fallen, and the project was ",
        " to other buildings.",
      ],
      options: ["adopt", "address", "extended", "visible", "ignore", "temporary", "propose", "random"],
      answers: ["address", "visible", "propose", "extended"],
      explanations: ["address a problem表示处理问题。", "系动词made后需要形容词作宾补。", "与changes搭配且语义为提出措施。", "被动结构was extended表示推广到其他楼宇。"],
    },
    {
      id: "read-cloze-peer-feedback",
      kind: "cloze",
      title: "选词填空：同伴反馈",
      type: "选词填空",
      theme: "学习方法",
      difficulty: "进阶",
      knowledgePoints: ["词性转换", "语义衔接", "动词搭配"],
      segments: [
        "Peer feedback is most useful when students receive a clear task. General comments such as 'good work' rarely help a writer ",
        " a draft. Reviewers should identify one strength, explain one point of confusion and offer a ",
        " suggestion. This structure keeps the discussion focused and makes criticism easier to ",
        ". It also reminds students that revision is a normal and ",
        " part of writing.",
      ],
      options: ["accept", "constructive", "essential", "revise", "silent", "reduce", "accidental", "observe"],
      answers: ["revise", "constructive", "accept", "essential"],
      explanations: ["help somebody do something后接动词原形。", "constructive suggestion为常用搭配。", "make criticism easier to accept语义完整。", "normal and essential由and连接两个形容词。"],
    },
    {
      id: "read-matching-learning-spaces",
      kind: "matching",
      title: "长篇匹配：学习空间的四种改造",
      type: "长篇匹配",
      theme: "校园学习",
      difficulty: "基础",
      knowledgePoints: ["关键词定位", "同义替换", "段落主旨"],
      paragraphs: [
        { id: "A", text: "One library replaced a rarely used information desk with standing tables. The change created a place for brief laptop work without occupying seats intended for long study sessions." },
        { id: "B", text: "A science building introduced small rooms that students can reserve for online interviews. Sound-absorbing walls reduce disturbance to nearby classes." },
        { id: "C", text: "An arts center placed movable boards between tables. Students can display sketches, rearrange the boards and create temporary project areas." },
        { id: "D", text: "A residence hall converted an empty storage room into a late-night quiet zone. Entry is limited to residents, and bright overhead lights were replaced with adjustable lamps." },
      ],
      statements: [
        { text: "This project supports students who need a private setting for remote professional communication.", answer: "B", explanation: "online interviews对应remote professional communication。" },
        { text: "This space allows users to change the physical arrangement for creative work.", answer: "C", explanation: "movable和rearrange对应change the physical arrangement。" },
        { text: "This change separates short computer use from longer periods of study.", answer: "A", explanation: "brief laptop work与long study sessions形成对应。" },
        { text: "This facility provides controlled access to quiet study after normal hours.", answer: "D", explanation: "late-night quiet zone和limited to residents对应题干。" },
      ],
    },
    {
      id: "read-matching-community-projects",
      kind: "matching",
      title: "长篇匹配：社区项目如何持续",
      type: "长篇匹配",
      theme: "社区参与",
      difficulty: "进阶",
      knowledgePoints: ["同义替换", "细节定位", "概念对应"],
      paragraphs: [
        { id: "A", text: "A tool-sharing group asks every new member to attend a safety demonstration. This reduces damage and gives participants confidence before they borrow equipment." },
        { id: "B", text: "A neighbourhood language club changes its topics every month but keeps the meeting time fixed. Organizers say predictable scheduling is more important than constant novelty." },
        { id: "C", text: "A food-waste project publishes a short report after each event. Volunteers can see how much food was redistributed and which collection points were least effective." },
        { id: "D", text: "A local history team records interviews in pairs. One person leads the conversation while the other checks sound quality and notes names that require verification." },
      ],
      statements: [
        { text: "Regular timing helps this activity remain dependable even when its content changes.", answer: "B", explanation: "fixed meeting time对应regular timing。" },
        { text: "Participants receive evidence about results and weak parts of the project.", answer: "C", explanation: "报告同时展示成果和低效收集点。" },
        { text: "Training is required before members can use shared resources.", answer: "A", explanation: "safety demonstration发生在borrow equipment之前。" },
        { text: "Two people divide communication and technical checking during the task.", answer: "D", explanation: "一人采访，一人检查录音和姓名。" },
      ],
    },
  ]),
  writing: Object.freeze([
    { id: "write-ai-study-boundaries", title: "智能工具与独立思考", type: "议论文", theme: "数字学习", difficulty: "进阶", knowledgePoints: ["平衡观点", "措施论证", "例证"], prompt: "Write an essay on how students can use intelligent digital tools while maintaining independent thinking.", hints: ["说明工具可以提高效率", "指出直接接受答案的风险", "提出核验、改写和独立作答规则"], outline: ["引言：效率与独立思考并不矛盾", "主体一：用于解释、反馈和资料整理", "主体二：先独立尝试，再核验来源", "结尾：工具服务于判断而非替代判断"], sample: "Intelligent digital tools can support learning, but students should not allow convenience to replace judgment. They can use such tools to clarify difficult concepts, organize information and receive feedback after making an independent attempt. Important claims should be checked against reliable sources, and generated answers should be rewritten in the student's own words. Used with clear boundaries, technology can strengthen rather than weaken independent thinking." },
    { id: "write-public-transport", title: "鼓励绿色出行", type: "问题解决", theme: "绿色城市", difficulty: "基础", knowledgePoints: ["问题分析", "措施建议", "因果表达"], prompt: "Write an essay on practical ways a city can encourage young people to use public transport more often.", hints: ["分析价格、便利性和信息问题", "提出至少两项措施", "说明措施如何改变行为"], outline: ["引言：选择取决于便利与成本", "措施一：学生票与换乘优惠", "措施二：实时信息和夜间班次", "结尾：可靠服务比口号更有效"], sample: "Young people are more likely to use public transport when it is affordable, reliable and easy to understand. Cities can offer student discounts and reduce the cost of transfers between buses and trains. Real-time arrival information and safe late-evening services are also important. These measures address practical barriers and make public transport a realistic daily choice rather than merely an environmental slogan." },
    { id: "write-campus-traditions", title: "校园传统是否需要更新", type: "观点讨论", theme: "文化传承", difficulty: "进阶", knowledgePoints: ["让步结构", "标准论证", "举例"], prompt: "Write an essay on whether universities should update campus traditions as student needs change.", hints: ["说明传统的共同记忆价值", "讨论排斥性或形式化风险", "提出保留核心、调整形式的标准"], outline: ["引言：传统可保留但不能僵化", "主体一：增强归属感", "主体二：根据参与度和公平性调整", "结尾：保存意义而非机械复制形式"], sample: "Campus traditions can create shared memories, but they should not remain unchanged simply because they are old. Universities should preserve activities that strengthen belonging while reviewing practices that exclude students or have lost their original purpose. The best approach is to protect the central value of a tradition and update its form so that more students can participate meaningfully." },
    { id: "write-short-video-learning", title: "短视频能否支持深度学习", type: "利弊分析", theme: "媒体素养", difficulty: "挑战", knowledgePoints: ["概念区分", "利弊分析", "条件结论"], prompt: "Write an essay on whether short educational videos can support deep learning.", hints: ["区分入门解释和系统学习", "说明碎片化风险", "提出视频与阅读、练习结合的方法"], outline: ["引言：短视频有用但功能有限", "优点：降低入门难度", "限制：缺少推理过程和练习", "结尾：作为入口而非完整课程"], sample: "Short educational videos can make a difficult topic less intimidating and help learners identify its basic structure. However, understanding a brief explanation is not the same as being able to apply an idea. Students should combine videos with sustained reading, note-taking and practice questions. In this way, short videos serve as an effective entry point without replacing the effort required for deep learning." },
    { id: "write-volunteer-quality", title: "志愿服务重数量还是质量", type: "观点讨论", theme: "社会责任", difficulty: "进阶", knowledgePoints: ["比较论证", "评价标准", "结果导向"], prompt: "Write an essay on why the quality of volunteer service may matter more than the number of activities completed.", hints: ["指出只计算次数的局限", "说明持续性和真实需求", "提出评价服务质量的标准"], outline: ["引言：数量方便统计但不代表价值", "主体：培训、持续参与和受益者反馈", "例子：长期数字技能辅导", "结尾：评价真实影响"], sample: "Counting volunteer activities is simple, but a high number does not guarantee meaningful service. Quality depends on whether volunteers understand real needs, receive suitable training and remain involved long enough to produce a result. A student who provides patient digital-skills support for several weeks may contribute more than someone who attends many unrelated events. Evaluation should therefore focus on preparation, continuity and impact." },
    { id: "write-failure-records", title: "记录失败为什么有价值", type: "说明论证", theme: "个人成长", difficulty: "基础", knowledgePoints: ["原因展开", "例子", "总结提升"], prompt: "Write an essay on the value of keeping a record of mistakes and failed attempts.", hints: ["说明记忆会淡化错误细节", "提出记录原因和纠正动作", "举学习或项目例子"], outline: ["引言：失败只有被分析才产生价值", "原因一：发现重复模式", "原因二：验证改进方法", "结尾：把挫折转化为证据"], sample: "A failed attempt becomes useful when it is recorded and examined. Memory often keeps the disappointment but loses the exact reason for the mistake. By noting what happened, why it happened and what action should be tested next, learners can identify repeated patterns and measure improvement. Such records turn failure from a vague negative experience into practical evidence for better decisions." },
  ]),
  translation: Object.freeze([
    { id: "trans-high-speed-rail", title: "高铁与区域联系", type: "社会发展", theme: "交通发展", difficulty: "进阶", knowledgePoints: ["不仅……还……", "被动表达", "区域联系"], source: "近年来，高速铁路进一步加强了中国不同地区之间的联系。它不仅缩短了城市间的旅行时间，也为沿线中小城市带来了新的发展机会。越来越多的人可以更加便利地求学、就业和旅游。", keyPoints: ["近年来与现在完成时", "not only...but also结构", "为城市带来机会", "并列三个行为"], reference: "In recent years, high-speed rail has further strengthened connections among different regions of China. It has not only shortened travel time between cities but also created new development opportunities for smaller cities along the routes. More people can now study, work and travel with greater convenience.", analysis: ["strengthen connections比make connections stronger简洁", "沿线可表达为along the routes", "最后一句使用并列动词避免重复can" ] },
    { id: "trans-intangible-heritage", title: "非物质文化遗产", type: "文化传承", theme: "传统文化", difficulty: "挑战", knowledgePoints: ["文化负载词", "定语从句", "传承表达"], source: "非物质文化遗产体现了一个地区长期形成的生活方式和审美观念。如今，许多年轻人通过短视频、展览和体验课程了解传统技艺。新的传播方式有助于扩大影响，但真正的传承仍离不开长期学习和实践。", keyPoints: ["非物质文化遗产准确表达", "长期形成的后置修饰", "通过多种方式了解", "离不开的自然表达"], reference: "Intangible cultural heritage reflects the ways of life and aesthetic values that a region has developed over a long period. Today, many young people learn about traditional crafts through short videos, exhibitions and hands-on courses. New forms of communication can broaden their influence, but genuine preservation still requires sustained learning and practice.", analysis: ["intangible cultural heritage为常用术语", "hands-on courses强调体验性", "requires比cannot leave更加自然" ] },
    { id: "trans-community-sports", title: "社区体育设施", type: "公共服务", theme: "健康生活", difficulty: "基础", knowledgePoints: ["随着……", "使役结构", "条件表达"], source: "随着人们更加重视健康，许多社区开始改善公共体育设施。步道、球场和小型健身区使居民能够在家附近锻炼。如果这些设施得到合理维护，它们还可以成为邻里交流的重要空间。", keyPoints: ["随着的状语结构", "enable somebody to do", "在家附近", "被动维护条件句"], reference: "As people place greater importance on health, many communities have begun to improve public sports facilities. Walking paths, courts and small fitness areas enable residents to exercise near their homes. If properly maintained, these facilities can also become important spaces for communication among neighbours.", analysis: ["place greater importance on表达更加重视", "If properly maintained为省略结构", "communication among neighbours强调多人之间" ] },
    { id: "trans-digital-government", title: "数字公共服务", type: "科技应用", theme: "数字社会", difficulty: "进阶", knowledgePoints: ["在线办理", "同时", "数字鸿沟"], source: "数字技术使许多公共服务可以在线办理，为居民节省了时间。同时，服务机构也需要关注不会熟练使用智能设备的人。只有保留必要的线下帮助，技术进步才能真正惠及更多群体。", keyPoints: ["使服务可以在线办理", "同时的转折衔接", "不熟练使用设备的人", "只有……才……"], reference: "Digital technology has made it possible for many public services to be handled online, saving residents time. At the same time, service providers need to consider people who are not confident users of smart devices. Only by preserving necessary offline assistance can technological progress truly benefit a wider range of people.", analysis: ["make it possible for...to...处理长主语", "not confident users比cannot use更准确", "Only by置于句首引起部分倒装" ] },
    { id: "trans-winter-tourism", title: "冰雪旅游", type: "地方发展", theme: "北方城市", difficulty: "基础", knowledgePoints: ["利用自然条件", "既……又……", "季节性经济"], source: "中国北方的一些城市充分利用冬季寒冷的自然条件，发展冰雪旅游。丰富的节庆和体育活动既吸引了游客，也为当地居民创造了新的就业机会。如何提高服务质量，是实现长期发展的关键。", keyPoints: ["充分利用", "发展某类旅游", "既吸引又创造", "如何……作主语"], reference: "Some cities in northern China make full use of their naturally cold winters to develop ice and snow tourism. A wide range of festivals and sports activities not only attract visitors but also create new employment opportunities for local residents. Improving service quality is essential to achieving long-term development.", analysis: ["make full use of为固定搭配", "not only...but also连接两个谓语", "将如何提高转为动名词主语更自然" ] },
    { id: "trans-science-education", title: "公共科学教育", type: "教育发展", theme: "科学素养", difficulty: "进阶", knowledgePoints: ["越来越多", "不仅限于", "激发兴趣"], source: "越来越多的博物馆和科研机构开始向公众开放科学教育活动。这些活动不仅介绍知识，还鼓励参与者提出问题、观察现象并进行简单实验。亲身参与能够激发青少年对科学的长期兴趣。", keyPoints: ["越来越多的机构", "向公众开放", "not only介绍还鼓励", "激发长期兴趣"], reference: "An increasing number of museums and research institutions are offering science education activities to the public. These activities not only introduce knowledge but also encourage participants to ask questions, observe phenomena and conduct simple experiments. Direct participation can inspire a lasting interest in science among young people.", analysis: ["an increasing number of后接复数", "conduct experiments为常用搭配", "inspire an interest in准确表达激发兴趣" ] },
  ]),
  speaking: Object.freeze([
    { id: "speak-study-setback", title: "一次学习挫折", type: "个人陈述", theme: "个人成长", difficulty: "基础", knowledgePoints: ["过去经历", "原因反思", "改进结果"], prompt: "Describe a learning setback that helped you improve your study method.", followUp: "Why do some students repeat the same mistake even after receiving feedback?", structure: ["说明任务和失败结果", "解释具体原因", "说明采取的改变", "总结后来取得的进步"], sample: "I once prepared for a presentation by reading my notes repeatedly, but I could not explain the topic clearly without them. I realized that recognition was not the same as active recall. After that, I practised speaking from a short outline and recorded myself. The experience taught me to test what I could produce rather than how familiar the material looked." },
    { id: "speak-city-space", title: "最需要改善的城市空间", type: "个人陈述", theme: "城市生活", difficulty: "进阶", knowledgePoints: ["问题描述", "方案建议", "受益群体"], prompt: "Describe one public space in your city that should be improved and explain how.", followUp: "Who should have the strongest voice in decisions about public spaces?", structure: ["指出具体空间", "描述当前问题", "提出两项改进", "说明哪些人会受益"], sample: "The area around a busy bus stop near my home should be improved. Passengers have little shelter in winter, and the route information is difficult to read at night. The city could add an enclosed waiting area and clearer electronic signs. These changes would especially help older passengers and people who are unfamiliar with the area." },
    { id: "speak-team-disagreement", title: "如何处理团队分歧", type: "观点问答", theme: "合作沟通", difficulty: "进阶", knowledgePoints: ["提出原则", "礼貌反驳", "达成决定"], prompt: "Explain how a student team should respond when members strongly disagree about a project plan.", followUp: "Is voting always the best way to make a group decision?", structure: ["先确认共同目标", "让双方说明证据", "比较时间与效果", "必要时小规模测试方案"], sample: "A team should first restate the common goal instead of treating disagreement as a personal conflict. Each side can explain its evidence and the practical consequences of its proposal. If possible, the group should test a small part of each idea. Voting may be useful, but discussion and evidence often produce a better decision than a quick majority." },
    { id: "speak-local-culture", title: "向外地朋友介绍本地文化", type: "个人陈述", theme: "文化交流", difficulty: "基础", knowledgePoints: ["介绍特色", "解释意义", "提出体验方式"], prompt: "Introduce one aspect of local culture that you would recommend to a visitor.", followUp: "How can local traditions remain attractive to young people?", structure: ["说明文化内容", "介绍形成背景", "说明推荐原因", "给出体验建议"], sample: "I would recommend experiencing winter public life in Changchun, including outdoor sports and seasonal cultural events. These activities show how residents adapt to a long, cold season and turn it into a shared social experience. A visitor should not only watch a performance but also try a simple activity and talk with local participants." },
    { id: "speak-responsible-technology", title: "负责任地使用新技术", type: "观点问答", theme: "科技伦理", difficulty: "挑战", knowledgePoints: ["界定责任", "风险举例", "规则建议"], prompt: "What does it mean for a university student to use new technology responsibly?", followUp: "Should universities restrict some uses of intelligent tools?", structure: ["定义负责任使用", "保护隐私和核验信息", "不让工具代替个人工作", "提出透明使用规则"], sample: "Responsible use means understanding both the benefits and the risks of a tool. Students should protect personal data, verify important information and clearly state when technology has assisted their work. Universities may restrict uses that replace assessment or expose private information, but they should also teach students how to use useful tools transparently." },
  ]),
});
