export const RESOURCE_CATALOG = Object.freeze([
  {
    id: "original-bank",
    title: "本站原创题库",
    description: "可直接在网站中作答、计时、评分和复盘。题目、例句与解析均由本项目独立制作。",
    type: "可直接训练",
    tone: "original",
    items: [
      { name: "词汇训练库", modules: "认读、拼写、听写、语境、搭配", access: "站内使用", detail: "首批40个核心词，持续扩充；每词记录复习历史和下次复习。" },
      { name: "听力原创训练", modules: "长对话、听力篇章、讲话/报道/讲座", access: "站内使用", detail: "题干、选项、听力文本、证据句、选项分析和错因。" },
      { name: "阅读原创训练", modules: "选词填空、长篇匹配、仔细阅读", access: "站内使用", detail: "文章、题目、证据句、同义替换和干扰项分析。" },
      { name: "写译口语原创训练", modules: "写作、汉译英、口试Part 1—3", access: "站内使用", detail: "题目、提纲、参考思路、示例文本和自评量表。" },
      { name: "阶段测验与模拟", modules: "周测、专项测、130分钟完整模拟", access: "站内使用", detail: "已提供固定题序、分段计时、断点保存、交卷统计和分项复盘；只标注为原创模拟，不冒充官方真题。" },
    ],
  },
  {
    id: "official-materials",
    title: "官方考试资料",
    description: "用于核对考试结构、题型、口试流程和考试要求。本站只提供索引，不复制官方完整材料。",
    type: "权威说明",
    tone: "official",
    items: [
      { name: "CET官方网站", modules: "考试通知、报名、成绩、考试介绍", access: "外部官网", url: "https://cet.neea.edu.cn/", detail: "考试信息的首要核对入口。" },
      { name: "六级笔试结构", modules: "写作、听力、阅读、翻译", access: "外部官网", url: "https://cet.neea.edu.cn/html1/report/16123/201-1.htm", detail: "核对题型、题量、时间和分值比例。" },
      { name: "六级口试结构", modules: "自我介绍、个人陈述、讨论、问答", access: "外部官网", url: "https://cet.neea.edu.cn/html1/report/16123/200-1.htm", detail: "核对口试任务与计时。" },
      { name: "CET考试大纲入口", modules: "能力要求与考试说明", access: "外部官网", url: "https://cet.neea.edu.cn/xhtml1/folder/16113/1588-1.htm", detail: "查看官方大纲与样题入口，以网页当期内容为准。" },
      { name: "全国报名系统", modules: "资格核验、报名、缴费", access: "外部官网", url: "https://cet-bm.neea.edu.cn/", detail: "学校与省份存在差异时，以系统和所在学校通知为准。" },
    ],
  },
  {
    id: "listening-speaking",
    title: "听力与口语练习网站",
    description: "用于补充真实语音、跟读、B2/C1能力训练。外部网站内容不属于本站题库。",
    type: "外部练习",
    tone: "listening",
    items: [
      { name: "British Council LearnEnglish", modules: "B2/C1听力、口语、词汇", access: "外部网站", url: "https://learnenglish.britishcouncil.org/", detail: "按能力等级选择材料，适合精听和口语表达补充。" },
      { name: "VOA Learning English", modules: "新闻听力、发音、词汇", access: "外部网站", url: "https://learningenglish.voanews.com/", detail: "适合听写、复述和美式发音练习；使用时核对具体内容版权标记。" },
      { name: "BBC Learning English", modules: "听力、发音、连读、表达", access: "外部网站", url: "https://www.bbc.co.uk/learningenglish/", detail: "适合短时高频听力和自然表达训练。" },
      { name: "YouGlish", modules: "单词和短语真实语境发音", access: "外部工具", url: "https://youglish.com/", detail: "输入单词或搭配，比较不同说话者的重音和连读。" },
    ],
  },
  {
    id: "commercial-tools",
    title: "商业题库与听力工具（外部使用）",
    description: "这些平台保留在原网站或App内使用；本站只提供入口、使用建议和个人学习记录，不镜像题目、音频、解析或付费内容。",
    type: "外部工具",
    tone: "reference",
    items: [
      { name: "星火英语", modules: "四六级真题、专项训练、课程与解析", access: "外部官网/App", url: "https://www.sparke.cn/", detail: "优先用于阶段性真题训练和考试流程模拟；分数可手动记录回本站。" },
      { name: "可可英语", modules: "四六级听力、听写、外刊与综合英语", access: "外部网站/App", url: "https://www.kekenet.com/", detail: "适合补充听写、新闻和外刊输入；材料版权以原站标注为准。" },
      { name: "每日英语听力", modules: "听力、变速、循环、听写、跟读", access: "外部App/网站", url: "https://www.eudic.net/v4/en/app/ting", detail: "适合磨耳朵和精听流程；不要将原站音频重新上传到本站或云端。" },
      { name: "贝壳网", modules: "教育资源、测评与学校学习资源", access: "外部平台", url: "https://www.bakclass.com/", detail: "更适合作为补充资源入口；如果你指的是其他“贝壳”产品，请以具体链接为准。" },
    ],
  },
  {
    id: "reading-writing",
    title: "阅读、写作与语法",
    description: "用于扩展英文输入、核对写作结构和语言问题，不作为CET官方评分来源。",
    type: "能力扩展",
    tone: "reading",
    items: [
      { name: "British Council Reading", modules: "B2/C1阅读", access: "外部网站", url: "https://learnenglish.britishcouncil.org/skills/reading", detail: "按等级训练主旨、细节和信息定位。" },
      { name: "British Council Writing", modules: "B2/C1写作", access: "外部网站", url: "https://learnenglish.britishcouncil.org/skills/writing", detail: "观察不同文本的组织方式和表达功能。" },
      { name: "Purdue Online Writing Lab", modules: "写作结构、语法与引用", access: "外部网站", url: "https://owl.purdue.edu/", detail: "适合查询段落、句子和常见语言问题。" },
      { name: "Project Gutenberg", modules: "公版英文阅读", access: "外部资料库", url: "https://www.gutenberg.org/", detail: "只选择明确属于公版范围的作品，并根据难度节选个人学习。" },
    ],
  },
  {
    id: "authoritative-dictionaries",
    title: "权威词典与英语学习工具",
    description: "用于核对词义、搭配、发音、语法和学术词汇；本站只保存个人学习记录，不复制词典整页内容。",
    type: "权威工具",
    tone: "reference",
    items: [
      { name: "Oxford Learner's Dictionaries", modules: "Oxford 3000/5000、释义、搭配、语法", access: "外部词典", url: "https://www.oxfordlearnersdictionaries.com/", detail: "适合六级词汇分层、英英释义和学术表达核对。" },
      { name: "Longman Dictionary of Contemporary English", modules: "学习者词典、发音、例句、搭配", access: "外部词典", url: "https://www.ldoceonline.com/", detail: "适合用受控词汇理解释义，并比较词语搭配。" },
      { name: "Merriam-Webster", modules: "美式释义、发音、同义词、用法", access: "外部词典", url: "https://www.merriam-webster.com/", detail: "适合核对美式发音、词义差别和用法说明。" },
      { name: "Collins Dictionary", modules: "释义、例句、搭配、语法模式", access: "外部词典", url: "https://www.collinsdictionary.com/", detail: "适合比较英汉释义、例句和常见搭配。" },
      { name: "Cambridge English Learning English", modules: "B1-C1活动、写作反馈、样题与词汇", access: "外部学习平台", url: "https://www.cambridgeenglish.org/learning-english/", detail: "可补充分级读写听说活动和写作自我反馈，不等同CET官方评分。" },
    ],
  },
  {
    id: "academic-open-learning",
    title: "学术听读与公开课程",
    description: "用于训练六级常见的科技、教育、社会、环境和学术讲座主题；公开课程仍需遵守各站许可和引用要求。",
    type: "学术输入",
    tone: "listening",
    items: [
      { name: "OpenLearn · The Open University", modules: "免费短课程、学习技巧、社会与科学主题", access: "公开课程", url: "https://www.open.edu/openlearn/free-courses", detail: "适合按主题进行泛读、听读和英文笔记；课程由英国开放大学提供。" },
      { name: "MIT OpenCourseWare", modules: "课程讲义、阅读清单、视频、作业", access: "开放课程", url: "https://ocw.mit.edu/", detail: "适合科技、工程、经济和学术讲座输入；优先选择带字幕或文字材料的课程。" },
      { name: "TED-Ed", modules: "短视频课程、科学、社会、心理与教育", access: "外部教育平台", url: "https://ed.ted.com/", detail: "适合短篇听力、主旨复述和观点表达；优先使用带课程问题的公开课。" },
      { name: "NPR Podcasts & Shows", modules: "新闻、访谈、科学、社会议题", access: "外部音频平台", url: "https://www.npr.org/podcasts-and-shows/", detail: "适合进阶泛听和报告类语流；先选短节目，再逐步适应自然语速。" },
      { name: "American English · U.S. Department of State", modules: "教师资源、美国英语、课堂活动", access: "官方教育资源", url: "https://americanenglish.state.gov/", detail: "适合补充美国英语、课堂活动和文化主题材料；使用时遵守站点条件。" },
      { name: "OpenStax", modules: "免费、同行评审大学教材", access: "开放教材", url: "https://openstax.org/", detail: "适合科技、生命科学、社会科学等主题精读；优先使用明确开放许可的教材。" },
    ],
  },
  {
    id: "dictionary-culture",
    title: "词典、语料与中国文化表达",
    description: "用于核对词义、发音、搭配和翻译主题表达，不整库复制第三方内容。",
    type: "查询工具",
    tone: "reference",
    items: [
      { name: "Cambridge Dictionary", modules: "释义、英美发音、例句", access: "外部词典", url: "https://dictionary.cambridge.org/", detail: "优先核对词性、常用义和搭配。" },
      { name: "China Daily Language", modules: "双语新闻、中国文化、翻译表达", access: "外部网站", url: "https://language.chinadaily.com.cn/", detail: "用于积累文化主题表达；站内只记录个人笔记和来源链接。" },
      { name: "LibriVox", modules: "公版有声读物", access: "外部资料库", url: "https://librivox.org/", detail: "核对具体作品状态后用于长篇听力和跟读。" },
    ],
  },
  {
    id: "local-materials",
    title: "用户本地资料",
    description: "用户个人购买、下载或整理的教材和题目仅在自己的设备中学习，不上传到公开仓库。",
    type: "个人资料",
    tone: "local",
    items: [
      { name: "本地教材索引", modules: "章节、页码和学习日映射", access: "后续功能", detail: "只记录文件名、章节和本地位置，不公开上传原文件。" },
      { name: "个人真题与错题", modules: "年份、题型、错因和复测", access: "后续功能", detail: "用户自行确认资料来源与使用权限。" },
      { name: "个人音频与口语录音", modules: "精听、跟读、口试复盘", access: "本地保存", detail: "录音保存在浏览器IndexedDB，不同步到公开GitHub。" },
    ],
  },
]);
